### ISSUE TITLE
Hide the model process information

### ISSUE THREAD

**Issue by yatingchen** [hongyuanjia/eplusr#108]
Do you have any idea to hide the IDF model process? I want to track the parallel running steps set by myself, and this processing information makes some troubles for it.

![image](https://user-images.githubusercontent.com/38569061/64493612-e18aed00-d247-11e9-813a-7df55cf8fbe7.png)

**Comment by hongyuanjia** [comment]
In the development version, I added an arg `echo` to control this. You can hide the process info by setting it to `FALSE`.

**Comment by hongyuanjia** [comment]
You can install the development version via `remotes::install_github("hongyuanjia/eplusr")`. If you still have problem, feel free to reopen this.
