### ISSUE TITLE
EPW files with non-integer timezones fail to load

### ISSUE THREAD

**Issue by bjurban** [hongyuanjia/eplusr#113]
Some EPW files have non-integer timezones. 
New Delhi, India, for example, is +5.5. See:
https://energyplus.net/weather-location/asia_wmo_region_2/IND//IND_New.Delhi.421820_IWEC

This EPW fails to load in `eplusr` with the error that the timezone is not in an integer-coercible format. 

Would it be possible to switch the timezone format from integer to decimal to increase compatibility?

**Comment by hongyuanjia** [comment]
Thanks for your suggestion. Easy to change.

You can try the development version via `remotes::install_github("hongyuanjia/eplusr")`.

Feel free to reopen it if you still have problems.

**Comment by bjurban** [comment]
Awesome - the fix works great.
Really like this package - a huge time-saver!

Bryan

**Comment by hongyuanjia** [comment]
Glad to hear this package helps.
