### ISSUE TITLE
Calling NodeList returns unnamed list

### ISSUE THREAD

**Issue by bdcoelho** [hongyuanjia/eplusr#16]
While calling objects of class NodeList, the list returned is not a correctly name list. The NodeList names in the list returned are "NA". This does not allow NodeList objects to be called by their unique name.
See attached image "NodeList.png".
![nodelist](https://user-images.githubusercontent.com/12809853/43373785-477409f0-93ef-11e8-9126-5a6e68dea39a.png)

This works correctly for the other EnergyPlus objects that I've  called so far. See example of Branch object "Branch.png". 
![branch](https://user-images.githubusercontent.com/12809853/43373791-51d4bda4-93ef-11e8-83bf-bbed602c1634.png)

I'm not sure if this affects any other classes.

Regards,
Benson

**Comment by bdcoelho** [comment]
Works!
That was super quick, Thanks!

**Comment by hongyuanjia** [comment]
Glad to hear that. No worries ;)
