### ISSUE TITLE
"echo = F" can not work

### ISSUE THREAD

**Issue by yatingchen** [hongyuanjia/eplusr#168]
Hi,

I updated the package today into the newest version and the message shows below:
![image](https://user-images.githubusercontent.com/38569061/70092548-24a8f200-15e4-11ea-836e-dc91263a23b3.png)

Please check.
Thanks,
Yating

**Comment by hongyuanjia** [comment]
Hi @yatingchen. The newest CRAN version (0.10.4) did not contain any new functionalities compared to 0.10.3. The `echo` argument only works in the development version. Please use the development version.

I will update a new release to CRAN once all documentation refactor work finishes (See PR #156)
