### ISSUE TITLE
Idf class should not modify $clone() method

### ISSUE THREAD

**Issue by wch** [hongyuanjia/eplusr#19]
In [this code](https://github.com/hongyuanjia/eplusr/blob/7ba8ebb86f9fb290626811418485dd6696101684/R/idf.R#L1030-L1047), the `Idf` class modifies the `clone()` method. This is not something that is supported by R6. If users arbitrarily modify the internal code from the R6 clone method, it would be make it impossible to ever change or fix that method in the R6 package.

The reason that this comes up is because it fails with the current development version of R6, which has extensive changes to the clone method in order to fix some bugs. Please fix this; I will be submitting R6 to CRAN in the next week or so.

**Comment by hongyuanjia** [comment]
@wch Winston, thanks for letting me know.

Indeed, I knew that code is quite dirty. However, I did not come out a nice way to copy an `R6ClassGenerator` which is a private field of an `Idf` object. That `R6ClassGenerator` is specific to its parent `Idf` object with some shared data being set during the `Idf` initialization.

I will look into it and try to get it work for the new version of R6 package.
