### ISSUE TITLE
Can not change efficiency in IDF

### ISSUE THREAD

**Issue by yatingchen** [hongyuanjia/eplusr#20]
When I use `set_object()` to modify **Burner Efficiency** in class **Coil:Heating:Fuel**, the model can not run with several severe and fatal errors. But it can run under manually changing in IDF editor.

**Comment by hongyuanjia** [comment]
Thanks for reporting. I can confirm that it was caused by a bug when modifying objects that have references. 

It should be easy to fix.

**Comment by hongyuanjia** [comment]
Sorry for my late response.

This issue should be fixed via 8dc3254a1e429de280dfeeee482f492ca865e8ba.

Could you please install the develop version and do some simple testing?
