### ISSUE TITLE
Object WaterHeater:Mixed is not recognized

### ISSUE THREAD

**Issue by bdcoelho** [hongyuanjia/eplusr#22]
Hello

I'm trying to read in an idf that has a WaterHeater:Mixed object in it. I get the following error.

> model<-read_idf("HeatRecovery.idf") 
Error: IDF PARSING ERROR.
===================================================================
[ Error Type ]: Object type not recognized
[Total Number]: 6

Line 5143: HHW_Loop Supply Side HR Branch,
Line 5217: HHW_Loop Supply Side HR Branch,
Line 5278: HHW_Loop Supply Side HR Branch,
Line 7150: WaterHeater:Mixed,
Line 7331: WaterHeater:Mixed,
Line 7389: WaterHeater:Mixed,
===================================================================
> 

The object is valid in energyplus. What is even more strange is that if I format the IDF properly using the save feature in IDF Editor, it reads in perfectly fine! It is workable but the formatting shouldn't really matter in my opinion.

I've attached the IDF file as text. 

[HeatRecovery.txt](https://github.com/hongyuanjia/eplusr/files/2471018/HeatRecovery.txt)

Regards,
Benson

**Comment by hongyuanjia** [comment]
Thanks for reporting this bug.

Actually, by looking at your IDF file, those lines that caused the parsing error are IDF fields without field name comments, i.e. `!- Branch X Name` and etc. 

```
BranchList,
    HHW_Loop Supply Side Branches,  !- Name
    HHW_Loop Supply Side Inlet Branch,  !- Branch 1 Name
    HHW_Loop Supply Side HR Branch,
    HHW_Loop Supply Side Branch 1,  !- Branch 2 Name
    HHW_Loop Supply Side Branch 2,  !- Branch 3 Name
    HHW_Loop Supply Side Outlet Branch;  !- Branch 4 Name
```

eplusr trades those lines as class names, which can be problematic.

I am working on fixing that. Currently, for an workaround, I would suggest re-format the IDF using IDFEditor and edit the file using eplusr, or just add some field name comments after comma. Those comments are not parsed, just indicators that those are normal IDF fields.

**Comment by hongyuanjia** [comment]
In v0.10.0, parsing IDF has been totally refactored, which does not rely on any special comments. Close this.
