### ISSUE TITLE
Can I just output the successful run results in param runing?

### ISSUE THREAD

**Issue by yatingchen** [hongyuanjia/eplusr#24]
>  elec0 <- param$report_data(name = "Electricity:Facility")
> Error: Some of jobs completed unsuccessfully:
> 2|UNSUCCESSFUL --> [IDF]`set_parameters_2.idf` + [EPW]`IA_DES-MOINES-IAP_725460_10.epw`
> 4|UNSUCCESSFUL --> [IDF]`set_parameters_4.idf` + [EPW]`IA_DES-MOINES-IAP_725460_10.epw`
> 7|UNSUCCESSFUL --> [IDF]`set_parameters_7.idf` + [EPW]`IA_DES-MOINES-IAP_725460_10.epw`
> 8|UNSUCCESSFUL --> [IDF]`set_parameters_8.idf` + [EPW]`IA_DES-MOINES-IAP_725460_10.epw`

How can I get the other successful running models' results? Or are there any way to export which pairs unsuccessful?

Thanks

**Comment by hongyuanjia** [comment]
Yes, you can specify which job(s) you would like to export data from.

```r
elec0$report_data(which = c(1,3,5,6), name = NULL)
```

**Comment by yatingchen** [comment]
Thanks for your response!

I tested the suggestion you listed and decided to use: 
`eplusr:::._get_private(param)$m_job[exit_status != 0L]` 
to extract the unsuccessful runs.


But when I tried the 
`param$errors(c(2,4,7,8))`

but it only showed:

> Error: Some of jobs completed unsuccessfully:
> 2|UNSUCCESSFUL --> [IDF]`set_parameters_2.idf` + [EPW]`IA_DES-MOINES-IAP_725460_10.epw`
> 4|UNSUCCESSFUL --> [IDF]`set_parameters_4.idf` + [EPW]`IA_DES-MOINES-IAP_725460_10.epw`
> 7|UNSUCCESSFUL --> [IDF]`set_parameters_7.idf` + [EPW]`IA_DES-MOINES-IAP_725460_10.epw`
> 8|UNSUCCESSFUL --> [IDF]`set_parameters_8.idf` + [EPW]`IA_DES-MOINES-IAP_725460_10.epw`

I cannot see the details of errors.

**Comment by hongyuanjia** [comment]
It turns out that if EnergyPlus returns a non-zero, it means that the simulation cannot even start. So that’s why I decided to stop extracting any info from the err file when I designed the feature.

I would suggest to use `elec0$output_dir(open=TRUE)` to open the output folder and check each err file to find out the real problem.

Please tell me if the err file explains the problem. If so, I will consider to continue to parse the err file even EnergyPlus ended unsuccessfully.

**Comment by yatingchen** [comment]
> Error in param$output_dir(open = TRUE) : unused argument (open = TRUE)

it shows this.

**Comment by hongyuanjia** [comment]
Sorry, there should be no `open` argument. Please try directly go to the output dir and check the err file of each model that failed to run.

**Comment by yatingchen** [comment]
Yes, it shows the problem as the normal err files.

Thanks for your help.

**Comment by hongyuanjia** [comment]
@yatingchen, please check out the develop version. Now `$errors()` should work for unsuccessful jobs.
