### ISSUE TITLE
Error when saving epw files when headers are empty

### ISSUE THREAD

**Issue by lukas-rokka** [hongyuanjia/eplusr#263]
Saving epw files  doesn't work when the design, typical/extreme period or ground temperature headers are empty. Which is issue when working for example with AMY files from here [https://rokka.shinyapps.io/shinyweatherdata](https://rokka.shinyapps.io/shinyweatherdata)

---
The error is due to the following code on line 3121 in impl-epw.R (similair errors occurs on lines 3149 and 3165)

```r
if (length(design) == 0L) return("0")
```
Which return 1L when design header is empty. It can be fixed with for example unlisting before checking the lenght:
```r
if (length(unlist(design)) == 0L) return("0")
```

**Comment by hongyuanjia** [comment]
@lukas-rokka Thanks for the bug report and suggesting solutions.
