### ISSUE TITLE
Errors in reporting data

### ISSUE THREAD

**Issue by yatingchen** [hongyuanjia/eplusr#37]
I have some problems in reporting data a successful model running

When I used:
`job$report_data(name = "Electricity:Facility")`

I got errors like this:

> Error: Invalid date introduced with input start year:
> Original: 1-31 24:0 --> New year: 2019
> Original: 1-31 24:0 --> New year: 2019
> Original: 2-28 24:0 --> New year: 2019
> Original: 2-28 24:0 --> New year: 2019
> Original: 3-31 24:0 --> New year: 2019
> Original: 3-31 24:0 --> New year: 2019
> ...

When I typed:
`job$report_data("Electricity:Facility")`

But I cannot extract any information:

> Empty data.table (0 rows and 6 cols): case,datetime,key_value,name,units,value

What I want is to extract the electricity facilities' energy use simulation results from the meter data.

**Comment by hongyuanjia** [comment]
Thanks for reporting. There is a bug in `EplusSql` that input `key_value` and `name` did not take effect.

Actually, the function works fine on my site. I can get desired results by doing 

```r
job$report_data(name = "Electricity:Facility")
```

Please install the development version and give it a try. You can install it via: `remotes::install_github("hongyuanjia/eplusr")`.

**Comment by hongyuanjia** [comment]
Feel free to reopen this if you still have a problem in retrieving the data.

**Comment by yatingchen** [comment]
Thanks! It can work now!

**Comment by hongyuanjia** [comment]
Great! Thanks for letting me know this bug.
