### ISSUE TITLE
Help opening EPW computer file

### ISSUE THREAD

**Issue by MayTartarotti** [hongyuanjia/eplusr#393]
Hi! I came here because when I try to open an EPW file on my computer using the eplusr package, an error appears.
I think it's very likely that I'm doing something wrong, but I tried to follow the logic I read in the manual. I will attach below the form that I wrote the script, and the error message that appears when I run:

## The script

library(eplusr)

Arq<-system.file("FortalezaTRY1962_05CSV.epw", package = "eplusr")

read_epw(Arq)

## the message after running
> library(eplusr)
> 
> Arq<-system.file("FortalezaTRY1962_05CSV.epw", package = "eplusr")
> 
> read_epw(Arq)
Error in errorCondition(message, ..., class = unique(c(paste0("eplusr_error_",  : 
 unable to find function "errorCondition"

**Comment by hongyuanjia** [comment]
Hi @MayTartarotti. Actually, you are using the wrong function to specify the EPW file path. `system.file()` can be used to specify files that are distributed with the package itself.

You can simply give the file path:

```r
path <- "FortalezaTRY1962_05CSV.epw"

read_epw(path)

# OR directly
read_epw("FortalezaTRY1962_05CSV.epw")
```

Please make sure `FortalezaTRY1962_05CSV.epw` is located in current working directory. If not, specify the full path like `C:/Users/XXX/Documents/FortalezaTRY1962_05CSV.epw`

**Comment by MayTartarotti** [comment]
It worked, thank you very much! And congratulations on the development of this package, it is very complete and helps a lot!

**Comment by hongyuanjia** [comment]
Glad to know it works.
