### ISSUE TITLE
Error with upcoming units 0.7-0

### ISSUE THREAD

**Issue by Enchufa2** [hongyuanjia/eplusr#410]
We are preparing units 0.7-0 for release, and our revdep checks show a new error in `eplusr` (see [here](https://github.com/r-quantities/units/blob/master/revdep/problems.md#eplusr)). Please, review the [changes](https://github.com/r-quantities/units/blob/master/NEWS.md#version-07-0) to fix the issues and safely retain your package on CRAN.

**Comment by hongyuanjia** [comment]
Thanks @Enchufa2. Will upload a new version for compatibility
