### ISSUE TITLE
$run failed if the eplus path was not installed in default path ( C:/EnergyPlusV8-X-X )

### ISSUE THREAD

**Issue by jywang2016** [hongyuanjia/eplusr#5]
Hi! The $run function seems to work only if the Eplus is installed in the default path of the eplusr package. For example, the run function failed in my PC with Eplus installed in disk D, although I specified the eplus_home argument. BTW, I'm a Windows user.

**Comment by hongyuanjia** [comment]
It is a bug in the logic of finding EnergyPlus location in `eplusr`. It should be fixed now. If not, please let me know.

**Comment by jywang2016** [comment]
This bug has been fixed with the latest version.

**Comment by hongyuanjia** [comment]
Great to hear that.
