### ISSUE TITLE
some demo example and relate document request

### ISSUE THREAD

**Issue by ymg2007** [hongyuanjia/eplusr#6]
Hi, hongyuanjia.
    I am followed Jiangyu Wang's introduction to Github. I knew eplusr is so powerful package for EnergyPlus simulation and visualization.But some demo example is not available for the beginner. And there is no document to teach user how to use eplusr in the practical project.
   So please add some demo example and relate document!!!

**Comment by hongyuanjia** [comment]
Thanks @ymg2007 . Sorry for my late response.

Currently `eplusr` is under actively development, and lots of features are on there way. I will write some vignettes in the near future after finishing the parametric simulation functionality. But before that, the [README](https://github.com/hongyuanjia/eplusr/blob/master/README.md) should give you a comprehensive example showing the main functionalities.

The main goal of `eplusr` is to provide helpers and methods to modify EnergyPlus models, run them and collect simulation results directly in R. Unfortunately, it was not be able to do some magic stuff like directly setting HVAC system in [OpenStudio](https://www.openstudio.net/) or [`eppy`](https://github.com/santoshphilip/eppy) in python. You have to do all parts by your self.

As for visualization, you can take fully advantage of fantastic R packages like [`ggplot2`](http://ggplot2.tidyverse.org/) or [`plotly`](https://plot.ly/r/), as the simulation data collected by `eplusr$collect(long = TRUE)` is "ggplot2-friendly". Some features will be added to do basic visualization of simulation results in the future.

If you are interested, I shared the [document](https://1drv.ms/f/s!AlPDsV4LrMrnsI5667wkCGYDGPYdfA) I sent to Jiangyu which contains some details about running models and visualizations. You can see the results in the self-contained `eplusr_ggplot2.html` file. Also, you should be able to run all codes in `eplusr_ggplot2.Rmd` file when open it in RStudio. Hope that will give you a more clear image about how to use `eplusr`.

**Comment by hongyuanjia** [comment]
@ymg2007 , eplusr has been totally refactored and documents have been also updated. Please reopen it if you have any questions.
